name: irobman
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.5
  - pybullet
  - pip
  - pip:
      - matplotlib
      - pyyaml
      - open3d
      - trimesh
      - robotic
      - filterpy
